import { SearchHistory } from '../../model/entity/SearchHistory'

export const searchHistoryMockList: SearchHistory[] = [
  {
    historyId: 'history_001',
    userId: 'user_001',
    keyword: '周杰伦',
    lastSearchTime: '2026-06-03 10:10:00'
  },
  {
    historyId: 'history_002',
    userId: 'user_001',
    keyword: '爱乐之城',
    lastSearchTime: '2026-06-02 16:20:00'
  },
  {
    historyId: 'history_003',
    userId: 'user_001',
    keyword: '音乐节',
    lastSearchTime: '2026-06-01 13:00:00'
  },
  {
    historyId: 'history_004',
    userId: 'user_001',
    keyword: '北京',
    lastSearchTime: '2026-05-31 19:30:00'
  },
  {
    historyId: 'history_005',
    userId: 'user_001',
    keyword: '脱口秀',
    lastSearchTime: '2026-05-30 20:00:00'
  }
]
