import { Venue } from '../../model/entity/Venue'

export const venueMockList: Venue[] = [
  {
    venueId: 'venue_bj_001',
    venueName: '华熙LIVE·五棵松',
    cityName: '北京',
    address: '北京市海淀区复兴路69号',
    longitude: 116.2807,
    latitude: 39.9119,
  },
  {
    venueId: 'venue_bj_002',
    venueName: '北京保利剧院',
    cityName: '北京',
    address: '北京市东城区东直门南大街14号',
    longitude: 116.4336,
    latitude: 39.9402,
  },
  {
    venueId: 'venue_sh_001',
    venueName: '梅赛德斯-奔驰文化中心',
    cityName: '上海',
    address: '上海市浦东新区世博大道1200号',
    longitude: 121.4897,
    latitude: 31.1885,
  },
  {
    venueId: 'venue_gz_001',
    venueName: '广州大剧院',
    cityName: '广州',
    address: '广州市天河区珠江西路1号',
    longitude: 113.3220,
    latitude: 23.1134,
  },
  {
    venueId: 'venue_sz_001',
    venueName: '深圳湾体育中心',
    cityName: '深圳',
    address: '深圳市南山区滨海大道3001号',
    longitude: 113.9409,
    latitude: 22.5240,
  },
  {
    venueId: 'venue_cd_001',
    venueName: '成都金融城演艺中心',
    cityName: '成都',
    address: '成都市高新区天府大道北段1777号',
    longitude: 104.0669,
    latitude: 30.5763,
  }
]
