import { RefundRuleStage } from '../../model/entity/RefundRuleStage'

export const refundRuleStageMockList: RefundRuleStage[] = [
  {
    stageId: 'refund_stage_1001_72',
    refundRuleId: 'refund_rule_1001',
    beforeStartHours: 72,
    feeRate: 0
  },
  {
    stageId: 'refund_stage_1001_24',
    refundRuleId: 'refund_rule_1001',
    beforeStartHours: 24,
    feeRate: 0.2
  },
  {
    stageId: 'refund_stage_1003_48',
    refundRuleId: 'refund_rule_1003',
    beforeStartHours: 48,
    feeRate: 0
  },
  {
    stageId: 'refund_stage_1003_24',
    refundRuleId: 'refund_rule_1003',
    beforeStartHours: 24,
    feeRate: 0.3
  },
  {
    stageId: 'refund_stage_1004_24',
    refundRuleId: 'refund_rule_1004',
    beforeStartHours: 24,
    feeRate: 0
  },
  {
    stageId: 'refund_stage_1005_24',
    refundRuleId: 'refund_rule_1005',
    beforeStartHours: 24,
    feeRate: 0
  }
]
