import { BannerItem } from "../../model/entity/BannerItem";


export const bannerMockList: BannerItem[] = [
  {
    bannerId: 'banner_001',
    imageUrl: 'ZhouJieLunYanchu',
    relatedProjectId: 'proj_1001',
    sortOrder: 1,
    startTime: '2026-05-01 00:00:00',
    endTime: '2026-07-01 00:00:00'
  },
  {
    bannerId: 'banner_002',
    imageUrl: 'aiyueZhiChengYanchu',
    relatedProjectId: 'proj_1002',
    sortOrder: 2,
    startTime: '2026-05-01 00:00:00',
    endTime: '2026-07-01 00:00:00'
  },
  {
    bannerId: 'banner_003',
    imageUrl: 'YinyuejieYanchu',
    relatedProjectId: 'proj_1003',
    sortOrder: 3,
    startTime: '2026-05-01 00:00:00',
    endTime: '2026-07-01 00:00:00'
  }
]
