import { Category } from "../../model/entity/Category";


export const categoryMockList: Category[] = [
  {
    categoryId: 'cat_concert',
    categoryName: '演唱会',
    iconUrl: 'yanchanghui',
    sortOrder: 1
  },
  {
    categoryId: 'cat_drama',
    categoryName: '话剧',
    iconUrl: 'huajugeju',
    sortOrder: 2
  },
  {
    categoryId: 'cat_music_festival',
    categoryName: '音乐节',
    iconUrl: 'yinlejie',
    sortOrder: 3
  },
  {
    categoryId: 'cat_talkshow',
    categoryName: '脱口秀',
    iconUrl: 'tuokouxiu',
    sortOrder: 4
  },
  {
    categoryId: 'cat_immersive',
    categoryName: '沉浸剧场',
    iconUrl: 'hongsejuchang',
    sortOrder: 5
  },
  {
    categoryId: 'cat_crosstalk',
    categoryName: '相声',
    iconUrl: 'xiangsheng',
    sortOrder: 6
  },
  {
    categoryId: 'cat_opera',
    categoryName: '戏曲艺术',
    iconUrl: 'xiqu',
    sortOrder: 7
  },
  {
    categoryId: 'cat_dance',
    categoryName: '舞蹈舞剧',
    iconUrl: 'wudao',
    sortOrder: 8
  }
]
